/*
 * usps_mappings.h - USPS standard abbreviation mappings
 *
 * Used by parse_address_crf_normalized() to standardize address components.
 */

#ifndef USPS_MAPPINGS_H
#define USPS_MAPPINGS_H

#include <stddef.h>
#include <strings.h>

typedef struct {
  const char *input;
  const char *output;
} UspsMapping;

/* Street type abbreviations (StreetNamePostType) */
static const UspsMapping STREET_TYPE_MAPPINGS[] = {
    {"ALLEY", "ALY"},       {"ALLEE", "ALY"},
    {"ALLY", "ALY"},        {"ALY", "ALY"},
    {"ANEX", "ANX"},        {"ANNEX", "ANX"},
    {"ANNX", "ANX"},        {"ANX", "ANX"},
    {"ARCADE", "ARC"},      {"ARC", "ARC"},
    {"AVENUE", "AVE"},      {"AV", "AVE"},
    {"AVE", "AVE"},         {"AVEN", "AVE"},
    {"AVENU", "AVE"},       {"AVN", "AVE"},
    {"AVNUE", "AVE"},       {"BAYOU", "BYU"},
    {"BAYOO", "BYU"},       {"BEACH", "BCH"},
    {"BCH", "BCH"},         {"BEND", "BND"},
    {"BND", "BND"},         {"BLUFF", "BLF"},
    {"BLF", "BLF"},         {"BLUF", "BLF"},
    {"BLUFFS", "BLFS"},     {"BOTTOM", "BTM"},
    {"BOT", "BTM"},         {"BTM", "BTM"},
    {"BOTTM", "BTM"},       {"BOULEVARD", "BLVD"},
    {"BLVD", "BLVD"},       {"BOUL", "BLVD"},
    {"BOULV", "BLVD"},      {"BRANCH", "BR"},
    {"BR", "BR"},           {"BRNCH", "BR"},
    {"BRIDGE", "BRG"},      {"BRDGE", "BRG"},
    {"BRG", "BRG"},         {"BROOK", "BRK"},
    {"BRK", "BRK"},         {"BROOKS", "BRKS"},
    {"BURG", "BG"},         {"BURGS", "BGS"},
    {"BYPASS", "BYP"},      {"BYP", "BYP"},
    {"BYPA", "BYP"},        {"BYPAS", "BYP"},
    {"BYPS", "BYP"},        {"CAMP", "CP"},
    {"CP", "CP"},           {"CMP", "CP"},
    {"CANYON", "CYN"},      {"CANYN", "CYN"},
    {"CNYN", "CYN"},        {"CAPE", "CPE"},
    {"CPE", "CPE"},         {"CAUSEWAY", "CSWY"},
    {"CAUSWA", "CSWY"},     {"CSWY", "CSWY"},
    {"CENTER", "CTR"},      {"CEN", "CTR"},
    {"CENT", "CTR"},        {"CENTR", "CTR"},
    {"CENTRE", "CTR"},      {"CNTER", "CTR"},
    {"CNTR", "CTR"},        {"CTR", "CTR"},
    {"CENTERS", "CTRS"},    {"CIRCLE", "CIR"},
    {"CIR", "CIR"},         {"CIRC", "CIR"},
    {"CIRCL", "CIR"},       {"CRCL", "CIR"},
    {"CRCLE", "CIR"},       {"CIRCLES", "CIRS"},
    {"CLIFF", "CLF"},       {"CLF", "CLF"},
    {"CLIFFS", "CLFS"},     {"CLFS", "CLFS"},
    {"CLUB", "CLB"},        {"CLB", "CLB"},
    {"COMMON", "CMN"},      {"COMMONS", "CMNS"},
    {"CORNER", "COR"},      {"COR", "COR"},
    {"CORNERS", "CORS"},    {"CORS", "CORS"},
    {"COURSE", "CRSE"},     {"CRSE", "CRSE"},
    {"COURT", "CT"},        {"CT", "CT"},
    {"COURTS", "CTS"},      {"CTS", "CTS"},
    {"COVE", "CV"},         {"CV", "CV"},
    {"COVES", "CVS"},       {"CREEK", "CRK"},
    {"CRK", "CRK"},         {"CRESCENT", "CRES"},
    {"CRES", "CRES"},       {"CRSENT", "CRES"},
    {"CRSNT", "CRES"},      {"CREST", "CRST"},
    {"CROSSING", "XING"},   {"CRSSNG", "XING"},
    {"XING", "XING"},       {"CROSSROAD", "XRD"},
    {"CROSSROADS", "XRDS"}, {"CURVE", "CURV"},
    {"DALE", "DL"},         {"DL", "DL"},
    {"DAM", "DM"},          {"DM", "DM"},
    {"DIVIDE", "DV"},       {"DIV", "DV"},
    {"DV", "DV"},           {"DVD", "DV"},
    {"DRIVE", "DR"},        {"DR", "DR"},
    {"DRIV", "DR"},         {"DRV", "DR"},
    {"DRIVES", "DRS"},      {"ESTATE", "EST"},
    {"EST", "EST"},         {"ESTATES", "ESTS"},
    {"ESTS", "ESTS"},       {"EXPRESSWAY", "EXPY"},
    {"EXP", "EXPY"},        {"EXPR", "EXPY"},
    {"EXPRESS", "EXPY"},    {"EXPW", "EXPY"},
    {"EXPY", "EXPY"},       {"EXTENSION", "EXT"},
    {"EXT", "EXT"},         {"EXTN", "EXT"},
    {"EXTNSN", "EXT"},      {"EXTENSIONS", "EXTS"},
    {"EXTS", "EXTS"},       {"FALL", "FALL"},
    {"FALLS", "FLS"},       {"FLS", "FLS"},
    {"FERRY", "FRY"},       {"FRRY", "FRY"},
    {"FRY", "FRY"},         {"FIELD", "FLD"},
    {"FLD", "FLD"},         {"FIELDS", "FLDS"},
    {"FLDS", "FLDS"},       {"FLAT", "FLT"},
    {"FLT", "FLT"},         {"FLATS", "FLTS"},
    {"FLTS", "FLTS"},       {"FORD", "FRD"},
    {"FRD", "FRD"},         {"FORDS", "FRDS"},
    {"FOREST", "FRST"},     {"FORESTS", "FRST"},
    {"FRST", "FRST"},       {"FORGE", "FRG"},
    {"FORG", "FRG"},        {"FRG", "FRG"},
    {"FORGES", "FRGS"},     {"FORK", "FRK"},
    {"FRK", "FRK"},         {"FORKS", "FRKS"},
    {"FRKS", "FRKS"},       {"FORT", "FT"},
    {"FRT", "FT"},          {"FT", "FT"},
    {"FREEWAY", "FWY"},     {"FREEWY", "FWY"},
    {"FRWAY", "FWY"},       {"FRWY", "FWY"},
    {"FWY", "FWY"},         {"GARDEN", "GDN"},
    {"GARDN", "GDN"},       {"GRDEN", "GDN"},
    {"GRDN", "GDN"},        {"GARDENS", "GDNS"},
    {"GDNS", "GDNS"},       {"GRDNS", "GDNS"},
    {"GATEWAY", "GTWY"},    {"GATEWY", "GTWY"},
    {"GATWAY", "GTWY"},     {"GTWAY", "GTWY"},
    {"GTWY", "GTWY"},       {"GLEN", "GLN"},
    {"GLN", "GLN"},         {"GLENS", "GLNS"},
    {"GREEN", "GRN"},       {"GRN", "GRN"},
    {"GREENS", "GRNS"},     {"GROVE", "GRV"},
    {"GROV", "GRV"},        {"GRV", "GRV"},
    {"GROVES", "GRVS"},     {"HARBOR", "HBR"},
    {"HARB", "HBR"},        {"HARBR", "HBR"},
    {"HBR", "HBR"},         {"HRBOR", "HBR"},
    {"HARBORS", "HBRS"},    {"HAVEN", "HVN"},
    {"HVN", "HVN"},         {"HEIGHTS", "HTS"},
    {"HT", "HTS"},          {"HTS", "HTS"},
    {"HIGHWAY", "HWY"},     {"HIGHWY", "HWY"},
    {"HIWAY", "HWY"},       {"HIWY", "HWY"},
    {"HWAY", "HWY"},        {"HWY", "HWY"},
    {"HILL", "HL"},         {"HL", "HL"},
    {"HILLS", "HLS"},       {"HLS", "HLS"},
    {"HOLLOW", "HOLW"},     {"HLLW", "HOLW"},
    {"HOLLOWS", "HOLW"},    {"HOLW", "HOLW"},
    {"HOLWS", "HOLW"},      {"INLET", "INLT"},
    {"INLT", "INLT"},       {"ISLAND", "IS"},
    {"IS", "IS"},           {"ISLND", "IS"},
    {"ISLANDS", "ISS"},     {"ISLNDS", "ISS"},
    {"ISS", "ISS"},         {"ISLE", "ISLE"},
    {"ISLES", "ISLE"},      {"JUNCTION", "JCT"},
    {"JCT", "JCT"},         {"JCTION", "JCT"},
    {"JCTN", "JCT"},        {"JUNCTN", "JCT"},
    {"JUNCTON", "JCT"},     {"JUNCTIONS", "JCTS"},
    {"JCTNS", "JCTS"},      {"JCTS", "JCTS"},
    {"KEY", "KY"},          {"KY", "KY"},
    {"KEYS", "KYS"},        {"KYS", "KYS"},
    {"KNOLL", "KNL"},       {"KNL", "KNL"},
    {"KNOL", "KNL"},        {"KNOLLS", "KNLS"},
    {"KNLS", "KNLS"},       {"LAKE", "LK"},
    {"LK", "LK"},           {"LAKES", "LKS"},
    {"LKS", "LKS"},         {"LAND", "LAND"},
    {"LANDING", "LNDG"},    {"LNDG", "LNDG"},
    {"LNDNG", "LNDG"},      {"LANE", "LN"},
    {"LN", "LN"},           {"LIGHT", "LGT"},
    {"LGT", "LGT"},         {"LIGHTS", "LGTS"},
    {"LOAF", "LF"},         {"LF", "LF"},
    {"LOCK", "LCK"},        {"LCK", "LCK"},
    {"LOCKS", "LCKS"},      {"LCKS", "LCKS"},
    {"LODGE", "LDG"},       {"LDG", "LDG"},
    {"LDGE", "LDG"},        {"LODG", "LDG"},
    {"LOOP", "LOOP"},       {"LOOPS", "LOOP"},
    {"MALL", "MALL"},       {"MANOR", "MNR"},
    {"MNR", "MNR"},         {"MANORS", "MNRS"},
    {"MNRS", "MNRS"},       {"MEADOW", "MDW"},
    {"MEADOWS", "MDWS"},    {"MDW", "MDWS"},
    {"MDWS", "MDWS"},       {"MEDOWS", "MDWS"},
    {"MEWS", "MEWS"},       {"MILL", "ML"},
    {"MILLS", "MLS"},       {"MISSION", "MSN"},
    {"MISSN", "MSN"},       {"MSSN", "MSN"},
    {"MOTORWAY", "MTWY"},   {"MOUNT", "MT"},
    {"MNT", "MT"},          {"MT", "MT"},
    {"MOUNTAIN", "MTN"},    {"MNTAIN", "MTN"},
    {"MNTN", "MTN"},        {"MOUNTIN", "MTN"},
    {"MTIN", "MTN"},        {"MTN", "MTN"},
    {"MOUNTAINS", "MTNS"},  {"MNTNS", "MTNS"},
    {"NECK", "NCK"},        {"NCK", "NCK"},
    {"ORCHARD", "ORCH"},    {"ORCH", "ORCH"},
    {"ORCHRD", "ORCH"},     {"OVAL", "OVAL"},
    {"OVL", "OVAL"},        {"OVERPASS", "OPAS"},
    {"PARK", "PARK"},       {"PRK", "PARK"},
    {"PARKS", "PARK"},      {"PARKWAY", "PKWY"},
    {"PARKWY", "PKWY"},     {"PKWAY", "PKWY"},
    {"PKWY", "PKWY"},       {"PKY", "PKWY"},
    {"PARKWAYS", "PKWY"},   {"PKWYS", "PKWY"},
    {"PASS", "PASS"},       {"PASSAGE", "PSGE"},
    {"PATH", "PATH"},       {"PATHS", "PATH"},
    {"PIKE", "PIKE"},       {"PIKES", "PIKE"},
    {"PINE", "PNE"},        {"PINES", "PNES"},
    {"PNES", "PNES"},       {"PLACE", "PL"},
    {"PL", "PL"},           {"PLAIN", "PLN"},
    {"PLN", "PLN"},         {"PLAINS", "PLNS"},
    {"PLNS", "PLNS"},       {"PLAZA", "PLZ"},
    {"PLZ", "PLZ"},         {"PLZA", "PLZ"},
    {"POINT", "PT"},        {"PT", "PT"},
    {"POINTS", "PTS"},      {"PTS", "PTS"},
    {"PORT", "PRT"},        {"PRT", "PRT"},
    {"PORTS", "PRTS"},      {"PRTS", "PRTS"},
    {"PRAIRIE", "PR"},      {"PR", "PR"},
    {"PRR", "PR"},          {"RADIAL", "RADL"},
    {"RAD", "RADL"},        {"RADIEL", "RADL"},
    {"RADL", "RADL"},       {"RAMP", "RAMP"},
    {"RANCH", "RNCH"},      {"RANCHES", "RNCH"},
    {"RNCH", "RNCH"},       {"RNCHS", "RNCH"},
    {"RAPID", "RPD"},       {"RPD", "RPD"},
    {"RAPIDS", "RPDS"},     {"RPDS", "RPDS"},
    {"REST", "RST"},        {"RST", "RST"},
    {"RIDGE", "RDG"},       {"RDG", "RDG"},
    {"RDGE", "RDG"},        {"RIDGES", "RDGS"},
    {"RDGS", "RDGS"},       {"RIVER", "RIV"},
    {"RIV", "RIV"},         {"RVR", "RIV"},
    {"RIVR", "RIV"},        {"ROAD", "RD"},
    {"RD", "RD"},           {"ROADS", "RDS"},
    {"RDS", "RDS"},         {"ROUTE", "RTE"},
    {"ROW", "ROW"},         {"RUE", "RUE"},
    {"RUN", "RUN"},         {"SHOAL", "SHL"},
    {"SHL", "SHL"},         {"SHOALS", "SHLS"},
    {"SHLS", "SHLS"},       {"SHORE", "SHR"},
    {"SHOAR", "SHR"},       {"SHR", "SHR"},
    {"SHORES", "SHRS"},     {"SHOARS", "SHRS"},
    {"SHRS", "SHRS"},       {"SKYWAY", "SKWY"},
    {"SPRING", "SPG"},      {"SPG", "SPG"},
    {"SPNG", "SPG"},        {"SPRNG", "SPG"},
    {"SPRINGS", "SPGS"},    {"SPGS", "SPGS"},
    {"SPNGS", "SPGS"},      {"SPRNGS", "SPGS"},
    {"SPUR", "SPUR"},       {"SPURS", "SPUR"},
    {"SQUARE", "SQ"},       {"SQ", "SQ"},
    {"SQR", "SQ"},          {"SQRE", "SQ"},
    {"SQU", "SQ"},          {"SQUARES", "SQS"},
    {"SQRS", "SQS"},        {"STATION", "STA"},
    {"STA", "STA"},         {"STATN", "STA"},
    {"STN", "STA"},         {"STRAVENUE", "STRA"},
    {"STRA", "STRA"},       {"STRAV", "STRA"},
    {"STRAVEN", "STRA"},    {"STRAVN", "STRA"},
    {"STRVN", "STRA"},      {"STRVNUE", "STRA"},
    {"STREAM", "STRM"},     {"STREME", "STRM"},
    {"STRM", "STRM"},       {"STREET", "ST"},
    {"STRT", "ST"},         {"ST", "ST"},
    {"STR", "ST"},          {"STREETS", "STS"},
    {"SUMMIT", "SMT"},      {"SMT", "SMT"},
    {"SUMIT", "SMT"},       {"SUMITT", "SMT"},
    {"TERRACE", "TER"},     {"TER", "TER"},
    {"TERR", "TER"},        {"THROUGHWAY", "TRWY"},
    {"TRACE", "TRCE"},      {"TRACES", "TRCE"},
    {"TRCE", "TRCE"},       {"TRACK", "TRAK"},
    {"TRACKS", "TRAK"},     {"TRAK", "TRAK"},
    {"TRK", "TRAK"},        {"TRKS", "TRAK"},
    {"TRAFFICWAY", "TRFY"}, {"TRAIL", "TRL"},
    {"TRAILS", "TRL"},      {"TRL", "TRL"},
    {"TRLS", "TRL"},        {"TRAILER", "TRLR"},
    {"TRLR", "TRLR"},       {"TRLRS", "TRLR"},
    {"TUNNEL", "TUNL"},     {"TUNEL", "TUNL"},
    {"TUNL", "TUNL"},       {"TUNLS", "TUNL"},
    {"TUNNELS", "TUNL"},    {"TUNNL", "TUNL"},
    {"TURNPIKE", "TPKE"},   {"TRNPK", "TPKE"},
    {"TURNPK", "TPKE"},     {"UNDERPASS", "UPAS"},
    {"UNION", "UN"},        {"UN", "UN"},
    {"UNIONS", "UNS"},      {"VALLEY", "VLY"},
    {"VALLY", "VLY"},       {"VLLY", "VLY"},
    {"VLY", "VLY"},         {"VALLEYS", "VLYS"},
    {"VLYS", "VLYS"},       {"VIADUCT", "VIA"},
    {"VDCT", "VIA"},        {"VIA", "VIA"},
    {"VIADCT", "VIA"},      {"VIEW", "VW"},
    {"VW", "VW"},           {"VIEWS", "VWS"},
    {"VWS", "VWS"},         {"VILLAGE", "VLG"},
    {"VILL", "VLG"},        {"VILLAG", "VLG"},
    {"VILLG", "VLG"},       {"VILLIAGE", "VLG"},
    {"VLG", "VLG"},         {"VILLAGES", "VLGS"},
    {"VLGS", "VLGS"},       {"VILLE", "VL"},
    {"VL", "VL"},           {"VISTA", "VIS"},
    {"VIS", "VIS"},         {"VIST", "VIS"},
    {"VST", "VIS"},         {"VSTA", "VIS"},
    {"WALK", "WALK"},       {"WALKS", "WALK"},
    {"WALL", "WALL"},       {"WAY", "WAY"},
    {"WY", "WAY"},          {"WAYS", "WAYS"},
    {"WELL", "WL"},         {"WELLS", "WLS"},
    {"WLS", "WLS"},         {NULL, NULL} /* Sentinel */
};

/* Occupancy type abbreviations */
static const UspsMapping OCCUPANCY_TYPE_MAPPINGS[] = {
    {"APARTMENT", "APT"},   {"APT", "APT"},       {"BASEMENT", "BSMT"},
    {"BSMT", "BSMT"},       {"BUILDING", "BLDG"}, {"BLDG", "BLDG"},
    {"DEPARTMENT", "DEPT"}, {"DEPT", "DEPT"},     {"FLOOR", "FL"},
    {"FL", "FL"},           {"FRONT", "FRNT"},    {"FRNT", "FRNT"},
    {"HANGER", "HNGR"},     {"HNGR", "HNGR"},     {"KEY", "KEY"},
    {"LOBBY", "LBBY"},      {"LBBY", "LBBY"},     {"LOT", "LOT"},
    {"LOWER", "LOWR"},      {"LOWR", "LOWR"},     {"OFFICE", "OFC"},
    {"OFC", "OFC"},         {"PENTHOUSE", "PH"},  {"PH", "PH"},
    {"PIER", "PIER"},       {"REAR", "REAR"},     {"ROOM", "RM"},
    {"RM", "RM"},           {"SIDE", "SIDE"},     {"SLIP", "SLIP"},
    {"SPACE", "SPC"},       {"SPC", "SPC"},       {"STOP", "STOP"},
    {"SUITE", "STE"},       {"STE", "STE"},       {"TRAILER", "TRLR"},
    {"TRLR", "TRLR"},       {"UNIT", "UNIT"},     {"UPPER", "UPPR"},
    {"UPPR", "UPPR"},       {NULL, NULL} /* Sentinel */
};

/* Lookup function for street types */
static const char *lookup_street_type(const char *input) {
  for (int i = 0; STREET_TYPE_MAPPINGS[i].input != NULL; i++) {
    if (strcasecmp(input, STREET_TYPE_MAPPINGS[i].input) == 0) {
      return STREET_TYPE_MAPPINGS[i].output;
    }
  }
  return NULL;
}

/* Lookup function for occupancy types */
static const char *lookup_occupancy_type(const char *input) {
  for (int i = 0; OCCUPANCY_TYPE_MAPPINGS[i].input != NULL; i++) {
    if (strcasecmp(input, OCCUPANCY_TYPE_MAPPINGS[i].input) == 0) {
      return OCCUPANCY_TYPE_MAPPINGS[i].output;
    }
  }
  return NULL;
}

#endif /* USPS_MAPPINGS_H */
